# Generated by Django 2.2.12 on 2020-05-07 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='番組名')),
                ('corner_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='コーナー名')),
                ('address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='作成時間')),
                ('published_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
            ],
        ),
    ]
