# Generated by Django 2.2.12 on 2020-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='corner_title',
            field=models.CharField(max_length=200, verbose_name='コーナー名'),
        ),
    ]
