# Generated by Django 2.2.12 on 2020-05-07 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200508_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='作成時間'),
        ),
        migrations.AlterField(
            model_name='program',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新時間'),
        ),
    ]
