# Generated by Django 2.2.12 on 2020-05-16 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='program',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like_comment', to='myapp.Comment'),
        ),
    ]
