# Generated by Django 2.2.12 on 2020-05-16 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_auto_20200516_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
