# Generated by Django 2.2.12 on 2020-05-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200509_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.IntegerField(choices=[(0, '指定なし'), (1, 'TBSラジオ'), (2, 'ニッポン放送'), (3, '文化放送'), (4, 'NHK')], verbose_name='ラジオ局'),
        ),
    ]
