# Generated by Django 2.2.12 on 2020-05-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200509_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='program',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='myapp.Program'),
            preserve_default=False,
        ),
    ]
