# Generated by Django 2.2.12 on 2020-05-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_comment_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
