# Generated by Django 2.2.12 on 2020-05-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.IntegerField(choices=[(1, 'TBSラジオ'), (2, 'ニッポン放送'), (3, '文化放送'), (4, 'NHK')], verbose_name='ラジオ局')),
            ],
        ),
    ]
