# Generated by Django 2.2.12 on 2020-05-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_station_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='program',
        ),
    ]
