# Generated by Django 2.2.12 on 2020-05-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_station_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='program',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='myapp.Program'),
            preserve_default=False,
        ),
    ]
