# Generated by Django 2.2.12 on 2020-05-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_station_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='week',
        ),
    ]
