# Generated by Django 2.2.12 on 2020-05-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_station_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_choice', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='day_of_the_week',
            field=models.ManyToManyField(related_name='weeks', to='myapp.Week'),
        ),
    ]
