# Generated by Django 2.2.12 on 2020-05-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200510_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='week_choice',
        ),
        migrations.AddField(
            model_name='week',
            name='weeks',
            field=models.IntegerField(choices=[(1, '月'), (2, '火'), (3, '水'), (4, '木'), (5, '金'), (6, '土'), (7, '日')], null=True, verbose_name='曜日'),
        ),
        migrations.AlterField(
            model_name='station',
            name='day_of_the_week',
            field=models.ManyToManyField(related_name='day_of_the_week', to='myapp.Week'),
        ),
    ]
