# Generated by Django 2.2.12 on 2020-05-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200510_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='weeks',
            field=models.IntegerField(choices=[(1, '月'), (2, '火'), (3, '水'), (4, '木'), (5, '金'), (6, '土'), (7, '日')], null=True, unique=True, verbose_name='曜日'),
        ),
    ]
