# Generated by Django 2.2.12 on 2020-05-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200510_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='day_of_the_week',
            field=models.ManyToManyField(blank=True, null=True, related_name='day_of_the_week', to='myapp.Week'),
        ),
    ]
