# Generated by Django 2.2.12 on 2020-05-10 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20200510_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj_name', models.CharField(max_length=100, verbose_name='出演者')),
                ('main_dj', models.BooleanField(verbose_name='メインパーソナリティ')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='djs', to='myapp.Program')),
            ],
        ),
    ]
