# Generated by Django 2.2.12 on 2020-05-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_dj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='day_of_the_week',
            field=models.ManyToManyField(blank=True, null=True, related_name='曜日', to='myapp.Week'),
        ),
    ]
