# Generated by Django 2.2.12 on 2020-05-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20200510_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_name', models.CharField(max_length=100, verbose_name='主なハガキ職人')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='myapp.Program')),
            ],
        ),
    ]
