# Generated by Django 2.2.12 on 2020-05-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_listener'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='公式Webページ'),
        ),
    ]
