# Generated by Django 2.2.12 on 2020-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_program_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='day_of_the_week',
            field=models.ManyToManyField(blank=True, related_name='曜日', to='myapp.Week'),
        ),
    ]
