# Generated by Django 2.2.12 on 2020-05-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20200512_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='day_of_the_week',
            field=models.ManyToManyField(blank=True, related_name='day_of_the_weeks', to='myapp.Week', verbose_name='曜日'),
        ),
    ]
