# Generated by Django 2.2.12 on 2020-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20200512_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(choices=[('var', 'バラエティ'), ('mus', '音楽'), ('news', 'ニュース'), ('edu', '教育'), ('info', '情報'), ('hob', '趣味')], max_length=4, null=True, unique=True, verbose_name='ジャンル')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='genrelist',
            field=models.ManyToManyField(blank=True, related_name='genres', to='myapp.Genre', verbose_name='ジャンル'),
        ),
    ]
