# Generated by Django 2.2.12 on 2020-05-12 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0026_auto_20200512_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='okini_num',
            field=models.IntegerField(default=0, verbose_name='お気に入り'),
        ),
        migrations.CreateModel(
            name='Okini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Okini_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
