# Generated by Django 2.2.12 on 2020-05-12 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20200513_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okini',
            name='post',
        ),
        migrations.AddField(
            model_name='okini',
            name='program',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='okini_program', to='myapp.Program'),
        ),
        migrations.AlterField(
            model_name='okini',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okini_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
