# Generated by Django 2.2.12 on 2020-05-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20200513_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okini',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Program'),
        ),
    ]
