# Generated by Django 2.2.12 on 2020-05-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20200513_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okini',
            name='program',
        ),
    ]
