# Generated by Django 2.2.12 on 2020-05-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20200513_0054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Okini',
        ),
    ]
