# Generated by Django 2.2.12 on 2020-05-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_delete_okini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='okini_num',
        ),
    ]
